---

name: PR
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      
      - uses: hashicorp/setup-terraform@v3
      
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.2
        with:
          image-tag: 'latest'
      
      - run: terraform init

      - run: terraform validate

      - run: terraform test
